name: Build All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup crane
      uses: imjasonh/setup-crane@v0.4

    - name: Build
      run: ./super-builder.sh
